# Generated by Django 4.2.3 on 2023-08-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topic_name',
            new_name='Topic_name',
        ),
    ]
